### ISSUE TITLE
Error in IE7/8

### ISSUE THREAD

**Issue by keenwon** [webpack/script-loader#10]
```javascript
require('script!../libs/parsleyjs/dist/parsley.min.js')
```

```javascript
module.exports = function(src) {
	if (typeof execScript === "function")
		execScript(src);
	else
		eval.call(null, src);
}
```
`eval.call(null, src)` is not work in IE7/8

**Comment by rosenfeld** [comment]
I can confirm that. In IE8 `typeof execScript` is "object", not "function". The work-around I'm using to make it work in IE8 is using jQuery.globalEval implementation:

```javascript
require('jquery').globalEval(require('raw!./my-script.js'))
```

globalEval is implemented as:

```javascript
( window.execScript || function( data ) {window[ "eval" ].call( window, data );} )( data );
```

**Comment by hanleym** [comment]
I'm also having this issue and can confirm @rosenfeld's fix works.

**Comment by sokra** [comment]
IE8 is weird... why is it an `object`...

**Comment by sokra** [comment]
Next try: https://github.com/webpack/script-loader/commit/43e197d167fa78eb28364ca007b9042fdb3dd5af
