### ISSUE TITLE
Evaluating works inconsistently among browsers

### ISSUE THREAD

**Issue by valscion** [webpack/script-loader#6]
Please see the following blog post for explanation on why it is not possible to just run `eval.call(null, src)` and expect it to behave the same way in most of the browsers.

http://perfectionkills.com/global-eval-what-are-the-options/

It should be noted that even if the script written in that blog post is used, one should never rely 100% for this loader as it still might fail. Some kind of warning for unsupporting browsers could be given or maybe a plain-old script insertion should be done (if possible) for browsers which don't support indirect eval functionality nor `execScript`.

**Comment by cuongvo** [comment]
+1 for dynamic script insertion, similar to the way style-loader is doing it for CSS: https://github.com/webpack/style-loader/blob/master/addStyles.js

**Comment by dmose** [comment]
Another concrete consequence is that sites using Content-Security-Policy with the script loader are forced to weaken their security by adding 'unsafe-eval' to their CSP.  Given that the script loader is presumably used especially heavily by sites migrating to webpack, this may hurt uptake.

**Comment by wfalkwallace** [comment]
is there any update on this? February is a long time ago.

**Comment by zdexter** [comment]
+1, @dmose makes a good point about `Content-Security-Policy` settings. Latest Chrome will tell you:

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "`

**Comment by vagdwd** [comment]
+1 for issue faced by @zdexter . I might have to rethink usage of webpack for us. I would hate going back to requirejs.

**Comment by SPSpwetter** [comment]
Me three.

**Comment by valscion** [comment]
I think my original issue text seems incorrect, and this issue really seems to cover way more ground than just the `eval` call — mainly, the entire approach of injecting code by this loader.

Unfortunately as far as I know, the approach taken by `style-loader` as suggested by @cuongvo wouldn't work because the script contents can't be injected between the `<script></script>` opening and closing tags. Only way to get the browser to properly evaluate a dynamically inserted script tag would be to give that `script` tag a `src` referencing another file, which could itself be dynamically created... leading to a very different looking outcome.

At least the issues with the default `Content-Security-Policy` in Chrome should probably be mentioned in the README of this project. I'll close this issue as it doesn't really address the problems that have come up in the comments.
