### ISSUE TITLE
Does this work with online scripts?

### ISSUE THREAD

**Issue by trusktr** [webpack/script-loader#7]
For example, can I do `require('script!//maps.googleapis.com/maps/api/js?sensor=false&libraries=geometry')`?

**Comment by trusktr** [comment]
I found this: https://github.com/webpack/webpack/issues/150

**Comment by sokra** [comment]
webpack doesn't handle script loading. Use an separate library for this. i. e. https://github.com/ded/script.js/

**Comment by trusktr** [comment]
@sokra Thanks for the advice! I'm trying to avoid modifying the library, which is all AMD modules, and has some modules that load externals in this manner (using the requirejs async plugin). It'd be nice if webpack could bundle a handler that would fetch things in the browser for these types of cases. The problem is if I modify the way the library works, I might have to go and modify dozens of other code bases that depend on it, which I want to avoid. If webpack would work with this scenario without having to modify the library that'd be great!

I think I might be able to work around this by blacklisting the above example file in `externals`, then just loading it before the bundle, then AMD files depending on the above file would just get passed the external. I'll try that tomorrow.

**Comment by raulferras** [comment]
Hi @trusktr, did you manage to solve this issue? I'm having a similar one.
Thank you.

**Comment by johanroug** [comment]
take a look at externals. You can define a script in your html, and tell webpack that you have done so.

https://webpack.js.org/configuration/externals/
